export type { TreatmentResult } from "./types.js";
export { checkIn } from "./checkIn.js";
export { breathe } from "./breathe.js";
export { sauna } from "./sauna.js";
export { coldPlunge } from "./coldPlunge.js";
export { floatTank } from "./floatTank.js";
export { aromatherapy } from "./aromatherapy.js";
export { massage } from "./massage.js";
export { meditation } from "./meditation.js";
export { teaLounge } from "./teaLounge.js";
export { checkOut } from "./checkOut.js";
